// <auto-generated />
namespace Recommender.DataAccess.YahooMusic.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class GenreFieldNames : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(GenreFieldNames));
        
        string IMigrationMetadata.Id
        {
            get { return "201608251841182_GenreFieldNames"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
