// <auto-generated />
namespace Recommender.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _3updateschema : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_3updateschema));
        
        string IMigrationMetadata.Id
        {
            get { return "201604021044184_3-update-schema"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
